/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-07-2017
 * 
 * XDoclet definition:
 * @struts.form name="historyAddForm"
 */
public class HistoryAddForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** id property */
	private String id;

	/** text property */
	private String text;

	/** title property */
	private String title;

	/** identityId property */
	private String identityId;

	/** img property */
	private String img;

	/** date property */
	private String date;

	/** user property */
	private String user;

	/** els property */
	private String els;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the id.
	 * @return String
	 */
	public String getId() {
		return id;
	}

	/** 
	 * Set the id.
	 * @param id The id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/** 
	 * Returns the text.
	 * @return String
	 */
	public String getText() {
		return text;
	}

	/** 
	 * Set the text.
	 * @param text The text to set
	 */
	public void setText(String text) {
		this.text = text;
	}

	/** 
	 * Returns the title.
	 * @return String
	 */
	public String getTitle() {
		return title;
	}

	/** 
	 * Set the title.
	 * @param title The title to set
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/** 
	 * Returns the identityId.
	 * @return String
	 */
	public String getIdentityId() {
		return identityId;
	}

	/** 
	 * Set the identityId.
	 * @param identityId The identityId to set
	 */
	public void setIdentityId(String identityId) {
		this.identityId = identityId;
	}

	/** 
	 * Returns the img.
	 * @return String
	 */
	public String getImg() {
		return img;
	}

	/** 
	 * Set the img.
	 * @param img The img to set
	 */
	public void setImg(String img) {
		this.img = img;
	}

	/** 
	 * Returns the date.
	 * @return String
	 */
	public String getDate() {
		return date;
	}

	/** 
	 * Set the date.
	 * @param date The date to set
	 */
	public void setDate(String date) {
		this.date = date;
	}

	/** 
	 * Returns the user.
	 * @return String
	 */
	public String getUser() {
		return user;
	}

	/** 
	 * Set the user.
	 * @param user The user to set
	 */
	public void setUser(String user) {
		this.user = user;
	}

	/** 
	 * Returns the els.
	 * @return String
	 */
	public String getEls() {
		return els;
	}

	/** 
	 * Set the els.
	 * @param els The els to set
	 */
	public void setEls(String els) {
		this.els = els;
	}
}