/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-03-2017
 * 
 * XDoclet definition:
 * @struts.form name="leaveForm"
 */
public class LeaveForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** txtCode property */
	private String txtCode;

	/** txtUserName property */
	private String txtUserName;

	/** txtUserSex property */
	private String txtUserSex;

	/** txtUserTel property */
	private String txtUserTel;

	/** txtContent property */
	private String txtContent;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the txtCode.
	 * @return String
	 */
	public String getTxtCode() {
		return txtCode;
	}

	/** 
	 * Set the txtCode.
	 * @param txtCode The txtCode to set
	 */
	public void setTxtCode(String txtCode) {
		this.txtCode = txtCode;
	}

	/** 
	 * Returns the txtUserName.
	 * @return String
	 */
	public String getTxtUserName() {
		return txtUserName;
	}

	/** 
	 * Set the txtUserName.
	 * @param txtUserName The txtUserName to set
	 */
	public void setTxtUserName(String txtUserName) {
		this.txtUserName = txtUserName;
	}

	/** 
	 * Returns the txtUserSex.
	 * @return String
	 */
	public String getTxtUserSex() {
		return txtUserSex;
	}

	/** 
	 * Set the txtUserSex.
	 * @param txtUserSex The txtUserSex to set
	 */
	public void setTxtUserSex(String txtUserSex) {
		this.txtUserSex = txtUserSex;
	}

	/** 
	 * Returns the txtUserTel.
	 * @return String
	 */
	public String getTxtUserTel() {
		return txtUserTel;
	}

	/** 
	 * Set the txtUserTel.
	 * @param txtUserTel The txtUserTel to set
	 */
	public void setTxtUserTel(String txtUserTel) {
		this.txtUserTel = txtUserTel;
	}

	/** 
	 * Returns the txtContent.
	 * @return String
	 */
	public String getTxtContent() {
		return txtContent;
	}

	/** 
	 * Set the txtContent.
	 * @param txtContent The txtContent to set
	 */
	public void setTxtContent(String txtContent) {
		this.txtContent = txtContent;
	}
}