/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-09-2017
 * 
 * XDoclet definition:
 * @struts.form name="loginForm"
 */
public class LoginForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** identityId property */
	private String identityId;

	/** psw property */
	private String psw;

	/** user property */
	private String user;

	/** els property */
	private String els;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the identityId.
	 * @return String
	 */
	public String getIdentityId() {
		return identityId;
	}

	/** 
	 * Set the identityId.
	 * @param identityId The identityId to set
	 */
	public void setIdentityId(String identityId) {
		this.identityId = identityId;
	}

	/** 
	 * Returns the psw.
	 * @return String
	 */
	public String getPsw() {
		return psw;
	}

	/** 
	 * Set the psw.
	 * @param psw The psw to set
	 */
	public void setPsw(String psw) {
		this.psw = psw;
	}

	/** 
	 * Returns the user.
	 * @return String
	 */
	public String getUser() {
		return user;
	}

	/** 
	 * Set the user.
	 * @param user The user to set
	 */
	public void setUser(String user) {
		this.user = user;
	}

	/** 
	 * Returns the els.
	 * @return String
	 */
	public String getEls() {
		return els;
	}

	/** 
	 * Set the els.
	 * @param els The els to set
	 */
	public void setEls(String els) {
		this.els = els;
	}
}