/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-04-2017
 * 
 * XDoclet definition:
 * @struts.form name="newsPageForm"
 */
public class NewsPageForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** num property */
	private String num;

	/** add property */
	private String add;

	/** pageNum property */
	private String pageNum;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the num.
	 * @return String
	 */
	public String getNum() {
		return num;
	}

	/** 
	 * Set the num.
	 * @param num The num to set
	 */
	public void setNum(String num) {
		this.num = num;
	}

	/** 
	 * Returns the add.
	 * @return String
	 */
	public String getAdd() {
		return add;
	}

	/** 
	 * Set the add.
	 * @param add The add to set
	 */
	public void setAdd(String add) {
		this.add = add;
	}

	/** 
	 * Returns the pageNum.
	 * @return String
	 */
	public String getPageNum() {
		return pageNum;
	}

	/** 
	 * Set the pageNum.
	 * @param pageNum The pageNum to set
	 */
	public void setPageNum(String pageNum) {
		this.pageNum = pageNum;
	}
}