/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-07-2017
 * 
 * XDoclet definition:
 * @struts.form name="newsAddForm"
 */
public class NewsAddForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** id property */
	private String id;

	/** detail property */
	private String detail;

	/** fileurl property */
	private String fileurl;

	/** img property */
	private String img;

	/** newstext property */
	private String newstext;

	/** newsdata property */
	private String newsdata;

	/** user property */
	private String user;

	/** url property */
	private String url;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the id.
	 * @return String
	 */
	public String getId() {
		return id;
	}

	/** 
	 * Set the id.
	 * @param id The id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/** 
	 * Returns the detail.
	 * @return String
	 */
	public String getDetail() {
		return detail;
	}

	/** 
	 * Set the detail.
	 * @param detail The detail to set
	 */
	public void setDetail(String detail) {
		this.detail = detail;
	}

	/** 
	 * Returns the fileurl.
	 * @return String
	 */
	public String getFileurl() {
		return fileurl;
	}

	/** 
	 * Set the fileurl.
	 * @param fileurl The fileurl to set
	 */
	public void setFileurl(String fileurl) {
		this.fileurl = fileurl;
	}

	/** 
	 * Returns the img.
	 * @return String
	 */
	public String getImg() {
		return img;
	}

	/** 
	 * Set the img.
	 * @param img The img to set
	 */
	public void setImg(String img) {
		this.img = img;
	}

	/** 
	 * Returns the newstext.
	 * @return String
	 */
	public String getNewstext() {
		return newstext;
	}

	/** 
	 * Set the newstext.
	 * @param newstext The newstext to set
	 */
	public void setNewstext(String newstext) {
		this.newstext = newstext;
	}

	/** 
	 * Returns the newsdata.
	 * @return String
	 */
	public String getNewsdata() {
		return newsdata;
	}

	/** 
	 * Set the newsdata.
	 * @param newsdata The newsdata to set
	 */
	public void setNewsdata(String newsdata) {
		this.newsdata = newsdata;
	}

	/** 
	 * Returns the user.
	 * @return String
	 */
	public String getUser() {
		return user;
	}

	/** 
	 * Set the user.
	 * @param user The user to set
	 */
	public void setUser(String user) {
		this.user = user;
	}

	/** 
	 * Returns the url.
	 * @return String
	 */
	public String getUrl() {
		return url;
	}

	/** 
	 * Set the url.
	 * @param url The url to set
	 */
	public void setUrl(String url) {
		this.url = url;
	}
}