/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.sf.json.JSONSerializer;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dao.imp.BeautifulImp;
import com.entity.Beautiful;
import com.yourcompany.struts.form.BeautifulForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-06-2017
 * 
 * XDoclet definition:
 * @struts.action path="/beautiful" name="beautifulForm" input="/form/beautiful.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/successJsp.jsp"
 */
public class BeautifulAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		BeautifulForm beautifulForm = (BeautifulForm) form;// TODO Auto-generated method stub
		BeautifulImp n = new BeautifulImp();
		List<Beautiful> nlist = n.getAllBeautiful();
		String jsonString = null;
		Map<String, Object> map = new HashMap<String , Object>();
		map.put("result", nlist);
		jsonString = JSONSerializer.toJSON(map).toString();
		request.setAttribute("data", jsonString);
		System.out.println(jsonString);
		return mapping.findForward("success");
	}
}