/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.sf.json.JSONSerializer;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import com.dao.imp.BeautifulImp;
import com.entity.Beautiful;
import com.yourcompany.struts.form.BeautifulAddForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-07-2017
 * 
 * XDoclet definition:
 * @struts.action path="/template/beautifulAdd" name="beautifulAddForm" input="/form/beautifulAdd.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/template/adminSys.html"
 */
public class BeautifulAddAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		BeautifulAddForm beautifulAddForm = (BeautifulAddForm) form;// TODO Auto-generated method stub
		FormFile f = beautifulAddForm.getPhoto();
		String fileExt = f.getFileName().substring(f.getFileName().lastIndexOf(".") + 1);
		String fileName = UUID.randomUUID() + "." + fileExt;
		String filePath = super.getServlet().getServletContext().getRealPath("/images/wuhan/") + File.separator +fileName;
		System.out.println(filePath);
		String id = beautifulAddForm.getId();
		String name = beautifulAddForm.getName();
		String price = beautifulAddForm.getPrice();
		String location = beautifulAddForm.getLocation();
		String description = beautifulAddForm.getDescription();
		String img = "images/wuhan/" + fileName;
		String types = beautifulAddForm.getTypes();
		
		File file = new File(filePath);
		if(!file.getParentFile().exists()){
			file.getParentFile().mkdirs();
		}
		try {
			InputStream input = f.getInputStream();
			OutputStream output = new FileOutputStream(file);
			byte data[] = new byte [1024];
			int temp = 0;
			while((temp = input.read(data)) != -1){
				output.write(data,0,temp);
			}
			input.close();
			output.close();
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
		
		Beautiful n = new Beautiful(id, name, price, location, description, img, types);
		BeautifulImp b = new BeautifulImp();
		boolean flag = b.addBeau(n);
		
		String jsonString = null;
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("result", flag);
		jsonString = JSONSerializer.toJSON(map).toString();
		System.out.println(jsonString);
		request.setAttribute("data", jsonString);
		return mapping.findForward("success");
	}
}