/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.sf.json.JSONSerializer;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dao.imp.HistoricImp;
import com.entity.HistoryMessage;
import com.entity.News;
import com.yourcompany.struts.form.HistoryForm;
import com.yourcompany.struts.form.IntrAndHisForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-03-2017
 * 
 * XDoclet definition:
 * @struts.action path="/template/history" name="historyForm" input="/template/historic.html" scope="request" validate="true"
 * @struts.action-forward name="success" path="/successJsp.jsp"
 */
public class HistoryAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@SuppressWarnings("null")
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		IntrAndHisForm Form = (IntrAndHisForm) form;// TODO Auto-generated method stub
		String id = Form.getId();
		HistoricImp h = new HistoricImp();
		List<HistoryMessage> nlist = new ArrayList<HistoryMessage>();
		if(!id.equals("5")){
			nlist.add(h.getMessageById(Integer.parseInt(id)));
		} else {
			nlist = h.getAllMessage();
		}
//		System.out.println(id);
		
		String jsonString = null;
		Map<String, Object> map = new HashMap<String , Object>();
		map.put("result", nlist);
		jsonString = JSONSerializer.toJSON(map).toString();
		request.setAttribute("data", jsonString);
		return mapping.findForward("success");
	}
}