/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.sf.json.JSONSerializer;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dao.imp.NewImp;
import com.entity.News;
import com.yourcompany.struts.form.NewsDetailForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-03-2017
 * 
 * XDoclet definition:
 * @struts.action path="/newsDetail" name="newsDetailForm" input="/form/newsDetail.jsp" scope="request" validate="true"
 */
public class NewsDetailAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		NewsDetailForm newsDetailForm = (NewsDetailForm) form;// TODO Auto-generated method stub
		System.out.println(newsDetailForm.getNewsNum());
		NewImp n = new NewImp();
		String id = newsDetailForm.getNewsNum();
		String pre = (Integer.parseInt(id) - 1) + "";
		String next = (Integer.parseInt(id) + 1) + "";
		List<News> nlist = new ArrayList<News>();
		nlist.add(n.getNewsById(id));
		nlist.add(n.getNewsById(pre));
		nlist.add(n.getNewsById(next));
		String jsonString = null;
		Map<String, Object> map = new HashMap<String , Object>();
		map.put("result", nlist);
		jsonString = JSONSerializer.toJSON(map).toString();
		request.setAttribute("data", jsonString);
		return mapping.findForward("success");
	}
}